Small refactor of syzygy-index prior corrupt table debug
`target/release/helpmate_tb -m KQvKR`
135007759
thread 'main' panicked at 'Wrong position for the table, board 8/8/8/8/8/8/8/Kr1k4, turn White', src/indexer_syzygy.rs:482:33